import { describe, it, expect } from 'vitest';
import { parseLockfile, detectFormat } from '../src/detect.js';
import { splitKey } from '../src/formats/pnpm.js';
import { descriptorName } from '../src/formats/yarn.js';

const unwrap = (text: string, forced?: any) => {
  const r = parseLockfile(text, forced);
  if (!r.ok) throw new Error(r.error.message);
  return r.value;
};

const NPM_V3 = JSON.stringify({
  name: 'app', lockfileVersion: 3,
  packages: {
    '': { name: 'app', version: '1.0.0' },
    'node_modules/lodash': { version: '4.17.21', resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz', integrity: 'sha512-AAA' },
    'node_modules/@scope/pkg': { version: '2.0.0', integrity: 'sha512-BBB' },
    'node_modules/a/node_modules/nested': { version: '1.2.3', integrity: 'sha512-CCC' },
  },
});

const NPM_V1 = JSON.stringify({
  name: 'app', lockfileVersion: 1,
  dependencies: {
    lodash: { version: '4.17.21', integrity: 'sha512-AAA',
      dependencies: { inner: { version: '0.1.0', integrity: 'sha512-DDD' } } },
  },
});

const PNPM = `lockfileVersion: '6.0'

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-AAA}
    dev: false

  /@scope/pkg@2.0.0:
    resolution: {integrity: sha512-BBB}

  /react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-EEE}
`;

const YARN_V1 = `# THIS IS AN AUTOGENERATED FILE
# yarn lockfile v1

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c"
  integrity sha512-AAA

"@scope/pkg@^2.0.0", "@scope/pkg@^2.1.0":
  version "2.0.0"
  integrity sha512-BBB
`;

const YARN_BERRY = `__metadata:
  version: 6

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: abc123

"@scope/pkg@npm:^2.0.0":
  version: 2.0.0
  resolution: "@scope/pkg@npm:2.0.0"
  checksum: def456
`;

describe('format detection', () => {
  it('identifies each supported format from content alone', () => {
    expect(detectFormat(NPM_V3)).toBe('npm');
    expect(detectFormat(PNPM)).toBe('pnpm');
    expect(detectFormat(YARN_V1)).toBe('yarn');
    expect(detectFormat(YARN_BERRY)).toBe('yarn-berry');
  });
  it('gives up honestly on something else', () => {
    expect(detectFormat('hello world')).toBeUndefined();
    const r = parseLockfile('hello world');
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.hint).toMatch(/package-lock/);
  });
});

describe('npm', () => {
  it('reads the flat packages map of v2/v3', () => {
    const lock = unwrap(NPM_V3);
    expect(lock.byName.get('lodash')).toEqual(['4.17.21']);
    expect(lock.byName.get('@scope/pkg')).toEqual(['2.0.0']);
    expect(lock.lockfileVersion).toBe('3');
  });

  it('names a nested package by what it is, not where it sits', () => {
    // node_modules/a/node_modules/nested is "nested", not "a/node_modules/nested".
    expect(unwrap(NPM_V3).byName.has('nested')).toBe(true);
  });

  it('skips the root project entry', () => {
    expect(unwrap(NPM_V3).byName.has('app')).toBe(false);
  });

  it('walks the nested dependency tree of v1', () => {
    const lock = unwrap(NPM_V1);
    expect(lock.byName.get('lodash')).toEqual(['4.17.21']);
    expect(lock.byName.get('inner')).toEqual(['0.1.0']);
  });

  it('captures integrity and resolved', () => {
    const entry = unwrap(NPM_V3).entries.get('lodash@4.17.21');
    expect(entry?.integrity).toBe('sha512-AAA');
    expect(entry?.resolved).toContain('registry.npmjs.org');
  });
});

describe('pnpm', () => {
  it('reads packages and integrity', () => {
    const lock = unwrap(PNPM);
    expect(lock.byName.get('lodash')).toEqual(['4.17.21']);
    expect(lock.entries.get('lodash@4.17.21')?.integrity).toBe('sha512-AAA');
  });
  it('handles scoped names', () => {
    expect(unwrap(PNPM).byName.get('@scope/pkg')).toEqual(['2.0.0']);
  });
  it('strips peer suffixes from the key', () => {
    expect(unwrap(PNPM).byName.get('react-dom')).toEqual(['18.2.0']);
  });
  it('splits every key layout pnpm has used', () => {
    expect(splitKey('/lodash@4.17.21')).toEqual({ name: 'lodash', version: '4.17.21' });
    expect(splitKey('/@scope/pkg@2.0.0')).toEqual({ name: '@scope/pkg', version: '2.0.0' });
    expect(splitKey('lodash@4.17.21')).toEqual({ name: 'lodash', version: '4.17.21' });
    expect(splitKey('/lodash/4.17.21')).toEqual({ name: 'lodash', version: '4.17.21' });
  });
});

describe('yarn classic', () => {
  it('reads its indentation-based blocks', () => {
    const lock = unwrap(YARN_V1);
    expect(lock.byName.get('lodash')).toEqual(['4.17.21']);
    expect(lock.entries.get('lodash@4.17.21')?.integrity).toBe('sha512-AAA');
  });
  it('takes the name from a multi-descriptor header', () => {
    expect(unwrap(YARN_V1).byName.get('@scope/pkg')).toEqual(['2.0.0']);
  });
  it('ignores comments', () => {
    expect(unwrap(YARN_V1).byName.size).toBe(2);
  });
});

describe('yarn berry', () => {
  it('reads version and checksum, skipping __metadata', () => {
    const lock = unwrap(YARN_BERRY);
    expect(lock.byName.get('lodash')).toEqual(['4.17.21']);
    expect(lock.entries.get('lodash@4.17.21')?.integrity).toBe('abc123');
    expect(lock.byName.has('__metadata')).toBe(false);
  });
  it('strips the npm: protocol from the descriptor', () => {
    expect(descriptorName('@scope/pkg@npm:^2.0.0')).toBe('@scope/pkg');
    expect(descriptorName('lodash@npm:^4.17.21')).toBe('lodash');
  });
});

describe('failure modes', () => {
  it('reports a truncated file rather than returning nothing', () => {
    const r = parseLockfile('{"lockfileVersion": 3, "packages": {');
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.hint).toMatch(/partial copy-paste/i);
  });
  it('reports a well-formed file with no packages', () => {
    const r = parseLockfile('{"lockfileVersion": 3, "packages": {}}');
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.error.message).toMatch(/no packages/i);
  });
});
